[build]
  command = "npm run build"
  publish = ""

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/v7/*"
  to = "https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=TSLA"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"